"""second

Revision ID: 8902dbb1986e
Revises: 
Create Date: 2025-06-07 04:25:37.816777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8902dbb1986e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moisture_upper_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('moisture_lower_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('temperature_upper_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('temperature_lower_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('soil_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('crop_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('size_unit', sa.String(length=20), nullable=True))
        batch_op.drop_column('threshold')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('size_unit')
        batch_op.drop_column('crop_type')
        batch_op.drop_column('soil_type')
        batch_op.drop_column('temperature_lower_threshold')
        batch_op.drop_column('temperature_upper_threshold')
        batch_op.drop_column('moisture_lower_threshold')
        batch_op.drop_column('moisture_upper_threshold')

    # ### end Alembic commands ###
